name: Build and Test Main Branch
on: push
jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      ## Environment variable
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      GOOGLE_OAUTH2_CLIENT_ID: ${{secrets.GOOGLE_OAUTH2_CLIENT_ID}}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${{secrets.GOOGLE_OAUTH2_CLIENT_SECRET}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Test
        run: ./gradlew test
      - name: Test
        run: ./gradlew bootJar
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:latest